<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LAPTOP-P330KRMQ"><DocLocation><![CDATA[E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res25]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" started.]]></Details>
<Time><![CDATA[29-03-2022 - 17:22:07]]></Time>
<TimeTick>1648554727</TimeTick>
<NodeArgs eType="Transaction" icon="4" nRep="7" nType="Start Transaction" Source="Action1" SourceLine="3" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:32]]></Time>
<TimeTick>1648554872</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Users\Anamika\Desktop\Flight GUI.lnk",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Users\Anamika\Desktop\Flight GUI.lnk",1]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:32]]></Time>
<TimeTick>1648554872</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Users\Anamika\Desktop\Flight GUI.lnk",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:40]]></Time>
<TimeTick>1648554880</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:40]]></Time>
<TimeTick>1648554880</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["HP"]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:40]]></Time>
<TimeTick>1648554880</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:40]]></Time>
<TimeTick>1648554880</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:40]]></Time>
<TimeTick>1648554880</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="21" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:41]]></Time>
<TimeTick>1648554881</TimeTick>
<NodeArgs eType="User" icon="9" nRep="22" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:41]]></Time>
<TimeTick>1648554881</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:41]]></Time>
<TimeTick>1648554881</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="25" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:51]]></Time>
<TimeTick>1648554891</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="24" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[closeapp]]></Obj>
<Details ><![CDATA[Closeapp successful]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:51]]></Time>
<TimeTick>1648554891</TimeTick>
<NodeArgs eType="User" icon="9" nRep="28" status="Passed" >
<Disp><![CDATA[closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:52]]></Time>
<TimeTick>1648554892</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run "C:\Users\Anamika\Desktop\Flight GUI.lnk",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Users\Anamika\Desktop\Flight GUI.lnk",1]]></Details>
<Time><![CDATA[29-03-2022 - 17:24:52]]></Time>
<TimeTick>1648554892</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="32" status="Passed" >
<Disp><![CDATA[Run "C:\Users\Anamika\Desktop\Flight GUI.lnk",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="31" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:03]]></Time>
<TimeTick>1648554903</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:03]]></Time>
<TimeTick>1648554903</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["HP"]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:03]]></Time>
<TimeTick>1648554903</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object&nbsp;is&nbsp;disabled]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:03]]></Time>
<TimeTick>1648554903</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = OK<br>devname = okButton<br>]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:03]]></Time>
<TimeTick>1648554903</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="41" status="Warning" nType="Description" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="40" status="Failed" nType="Run Error" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="36" status="Failed" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:03]]></Time>
<TimeTick>1648554903</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled<BR/>Function file: E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl<BR/>Line (5): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfButton(&quot;OK&quot;).Click&quot;.]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:04]]></Time>
<TimeTick>1648554904</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="43" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="4" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[134506]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:04]]></Time>
<TimeTick>1648554904</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="42" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[134506]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:04]]></Time>
<TimeTick>1648554904</TimeTick>
<NodeArgs eType="User" icon="9" nRep="45" status="Passed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:26]]></Time>
<TimeTick>1648554926</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"WpfTabStrip"&nbsp;(of&nbsp;class&nbsp;WpfTabStrip).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:26]]></Time>
<TimeTick>1648554926</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = tab<br>devnamepath = ;;<br>devname = <br>]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:26]]></Time>
<TimeTick>1648554926</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="50" status="Warning" nType="Description" >
<Disp><![CDATA[WpfTabStrip]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="49" status="Failed" nType="Run Error" >
<Disp><![CDATA[WpfTabStrip]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" status="Failed" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:26]]></Time>
<TimeTick>1648554926</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;WpfTabStrip&quot; (of class WpfTabStrip).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl<BR/>Line (25): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfTabStrip(&quot;WpfTabStrip&quot;).Select &quot;SEARCH ORDER&quot;&quot;.]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:26]]></Time>
<TimeTick>1648554926</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="24" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[134506]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[byNumberRadio]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"byNumberRadio"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:48]]></Time>
<TimeTick>1648554948</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:48]]></Time>
<TimeTick>1648554948</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" status="Warning" nType="Parent description" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="12" nRep="56" status="Failed" nType="Run Error" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberRadio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="51" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[134506]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:48]]></Time>
<TimeTick>1648554948</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;byNumberRadio&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl<BR/>Line (26): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfRadioButton(&quot;byNumberRadio&quot;).Set&quot;.]]></Details>
<Time><![CDATA[29-03-2022 - 17:25:48]]></Time>
<TimeTick>1648554948</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="59" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="25" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"byNumberWatermark"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:10]]></Time>
<TimeTick>1648554970</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:10]]></Time>
<TimeTick>1648554970</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" status="Warning" nType="Parent description" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="68" status="Failed" nType="Run Error" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberWatermark]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="58" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:10]]></Time>
<TimeTick>1648554970</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;byNumberWatermark&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl<BR/>Line (27): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfEdit(&quot;byNumberWatermark&quot;).Set &quot;2&quot;&quot;.]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:10]]></Time>
<TimeTick>1648554970</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="71" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="26" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[SEARCH]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"SEARCH"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:31]]></Time>
<TimeTick>1648554991</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:31]]></Time>
<TimeTick>1648554991</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="81" status="Warning" nType="Parent description" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="80" status="Failed" nType="Run Error" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[SEARCH]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="70" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:31]]></Time>
<TimeTick>1648554991</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;SEARCH&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl<BR/>Line (28): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfButton(&quot;SEARCH&quot;).Click&quot;.]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:31]]></Time>
<TimeTick>1648554991</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="83" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="27" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(of&nbsp;class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:53]]></Time>
<TimeTick>1648555013</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:53]]></Time>
<TimeTick>1648555013</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="87" status="Warning" nType="Description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="86" status="Failed" nType="Run Error" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="82" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:53]]></Time>
<TimeTick>1648555013</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;HPE MyFlight Sample Applicatio&quot; (of class WpfWindow).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl<BR/>Line (15): &quot;	WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).Close&quot;.]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:53]]></Time>
<TimeTick>1648555013</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="89" status="Failed" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="14" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(of&nbsp;class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:53]]></Time>
<TimeTick>1648555013</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[29-03-2022 - 17:26:53]]></Time>
<TimeTick>1648555013</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="91" status="Warning" nType="Description" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="90" status="Failed" nType="Run Error" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[29-03-2022 - 17:27:03]]></Time>
<TimeTick>1648555023</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="93" Source="E:\UFT Classbook PDF\Anamika\KeywordDrivenFramework\FunctionLibrary\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>